### ISSUE TITLE
How to create DOT file from GraphMap?

### ISSUE THREAD

**Issue by autonomousapps** [petgraph/petgraph#465]
I hope this is more of a documentation request than a bug report. I am new to Rust, and trying to recreate an algorithm I've written in Kotlin to one written in Rust, as a learning exercise. It would be very useful to be able to see the output of my graph-creation algorithm with graphviz. I'm trying `DiGraphMap` because `DiGraph` wasn't enforcing uniqueness of nodes (my nodes are all strings, but I'm getting multiple nodes with the same label, because I think `DiGraph` is treating their identifiers as labels rather than as identities, so that's why I'm trying `DiGraphmap`, because it _looks like_ that treats the identifier as, well, an identifier).

tl;dr I don't know how to use `Dot` with a `DiGraphMap`. The rust compiler is complaining that the `String` type doesn't implement `Copy`, but how can I work around that with this crate?

### Test Case

```rust
use petgraph::dot::Dot;
use petgraph::prelude::*;

let mut g = DiGraphMap::new();
let a = g.add_node("a".to_string());
let b = g.add_node("b".to_string());
g.add_edge(a, b, "".to_string());
println!("{}", Dot::new(&g));
```

### Steps To Reproduce

Insert instructions for reproducing the bug with the above test case:

* First, run the code above.
* Then, observe the error output.

### Actual Results

```
error[E0277]: the trait bound `String: Copy` is not satisfied
  --> src/main.rs:62:18
   |
62 |   println!("{}", Dot::new(&g));
   |                  ^^^^^^^^^^^^ the trait `Copy` is not implemented for `String`
   |
   = note: required because of the requirements on the impl of `Data` for `GraphMap<String, _, Directed>`
   = note: required because of the requirements on the impl of `std::fmt::Display` for `Dot<'_, &GraphMap<String, _, Directed>>`
   = note: required by `std::fmt::Display::fmt`
   = note: this error originates in the macro `$crate::format_args_nl` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Expected Results

When I do this with a `DiGraph`, I get dot output like
```
digraph {
 ...
}
```

and I want that for my `DiGraphMap`, too.

**Comment by autonomousapps** [comment]
As an aside, Rust Analyzer complains about using `Dot` with `DiGraph`, too, but the code actually compiles. Not sure what's up with that, but I lost a lot of time trying to get my IDE (IntelliJ IDEA) to stop complaining when it turns out it didn't matter.

**Comment by saona-raimundo** [comment]
Hi @autonomousapps!

I am no maintainer, but I thought I could give a hand.

So your request is to print the Dot format of a `DiGraphMap<String, String>`, right? 

The thing is... that `DiGraphMap<String, String>` can not even exist! Looking at [GraphMap documentation](https://docs.rs/petgraph/0.6.0/petgraph/graphmap/struct.GraphMap.html) you read this:
> The node weight `N` must implement `Copy` and will be used as node identifier, duplicated into several places in the data structure.

So yes, `N` is used as an identifier, but no, `N` can not be a `String` as it does not implement `Copy`.

## `String` and `Copy`

There is a nice [paragraph in `Copy` documentation](https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html#when-cant-my-type-be-copy) mentioning exactly why `String` does not implement `Copy`.

## Workaround

There is no real workaround for this case, that I am aware of. The best is to ask yourself why you need the nodes themselves to be `String`.
- Maybe you know all the strings at runtime and can use `&str` instead?
- Maybe there is another way for you to check the equality of nodes?


## Side note

If I try your example in the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=748ada17c05d7bb08982f62dfd860e9e), I get a equivalent but slightly different compilation error:
```
Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `String: NodeTrait` is not satisfied
 --> src/main.rs:8:24
  |
8 |     let a = g.add_node("a".to_string());
  |               -------- ^^^^^^^^^^^^^^^ expected an implementor of trait `NodeTrait`
  |               |
  |               required by a bound introduced by this call
  |
  = note: required because of the requirements on the impl of `NodeTrait` for `String`
help: consider borrowing here
  |
8 |     let a = g.add_node(&"a".to_string());
  |                        +
(...)
```

I know that it is not what you want, but the suggestion is to use `&str` instead of `String`. Why? Basically because `String` does not implement `Copy`, as your message says. Why is this needed? 
- `String` does not implement `Copy`
- => `String` does not implement `NodeTrait`
- => `DiGraphMap<String, String>` does not implement `IntoNodeReferences`
- => `DiGraphMap<String, String>` can not be passed to `Dot::new`.

**Comment by autonomousapps** [comment]
@saona-raimundo I appreciate the reply. I've taken a pause in my Rust journey, but since I wrote that post I also learned a lot, including why `String` doesn't implement `Copy` :) Rust has a lot of traits!

To reduce noise for the maintainer, I will close this issue for now. Again, much appreciated!
