### ISSUE TITLE
Graph coloring algorithm

### ISSUE THREAD

**Issue by jake-87** [petgraph/petgraph#673]
### A, or a set of, graph coloring algorithm(s).

Graph coloring is a problem that comes up in quite a few different areas, and it would be nice to have at least one built-in algorithm for this. Obviously it would most likely need to be a heuristic algorithm, as having something exponential in a library seems sub-ideal.

### Motivation

Graph coloring appears in many places, such as in register allocation. Not having to manually implement a function for this would be useful.

### Details

There appears to already be a PR for a coloring algorithm - #608. However, it seems to have stalled. 
It implements DSatur (https://en.wikipedia.org/wiki/DSatur), which I would think to be a good candidate. I am unfortunately too busy to implement this myself, but it's not extremely complex.

**Comment by XVilka** [comment]
Another option would be to implement Recursive Largest First (RLF) algorithm, since it produces better results while slightly (but not that much) more complex than DSatur: O(n^3) vs O(n^2). It should be noted though, that it's possible to implement both in more efficient ways, which reduces complexity significantly.

**Comment by XVilka** [comment]
Fixed by https://github.com/petgraph/petgraph/commit/159341e4af2a1292d8a1da428d64784e2dfc8ae5

If you have any issues with this implementation or have proposals for other algorithms, please open a new issue.
